apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: y052ch9jn-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/y052ch9jn-dotnet-basic-gitops